version: '3.1'
services:
  stats-client:
    build: ./stat/stats-client
    image: stats-client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
      - ewm-service
    environment:
      - STATS_SERVER_URL=http://stats-server:9091

  stats-server:
    build: ./stat/stats-server
    image: stats-server
    ports:
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./ewm-service
    image: ewm-service
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
